apiVersion: v1
kind: Service
metadata:
  name: star-wars-microservice-service
spec:
  type: NodePort
  selector:
    app: star-wars-microservice
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000